// Generated by scripts/generate-reference.mjs from the JSDoc beside each value. Do not edit.

/** Each token a theme may set: its group and what it is for. */
export const tokenDescriptions: Record<string, readonly [group: string, description: string]> = {
  '--color-background': ['color', 'The face of a window: the page behind the content.'],
  '--color-desktop': ['color', 'The desktop a window sits on. Docs and demo backdrops.'],
  '--color-card': [
    'color',
    'Panels and dialogs. Same face as the window; the bevel separates them.',
  ],
  '--color-muted': ['color', 'Toolbars and table headers.'],
  '--color-accent': [
    'color',
    'Row hover. Windows 98 has none — the token is here to be repointed.',
  ],
  '--color-surface-active': [
    'color',
    'A pressed row or toggle. The pressed bevel carries the state, not the fill.',
  ],
  '--color-surface-selected': [
    'color',
    'A selected row or list item: navy, with `on-selected` text.',
  ],
  '--color-surface-disabled': [
    'color',
    'A disabled control keeps the face colour; its text goes grey and embossed.',
  ],
  '--color-skeleton': ['color', 'Loading placeholder fill.'],
  '--color-input': [
    'color',
    'The inside of a text field, list or table body: white inside a sunken bevel.',
  ],
  '--color-tooltip-bg': ['color', 'Tooltip bubble.'],
  '--color-foreground': ['color', 'Body and heading text.'],
  '--color-muted-foreground': [
    'color',
    'Secondary text. Black, like body text: Windows 98 never greys out text that can still be read and acted on — grey means disabled.',
  ],
  '--color-text-subtle': ['color', 'Placeholders and de-emphasised metadata.'],
  '--color-text-disabled': [
    'color',
    "Disabled text, always drawn with {@link semanticColor ['text-disabled-emboss']} under it.",
  ],
  '--color-text-disabled-emboss': [
    'color',
    'The white copy, one pixel right and down, that embosses disabled text.',
  ],
  '--color-on-selected': ['color', 'Text on a selected row.'],
  '--color-link': ['color', 'Hyperlinks.'],
  '--color-border': [
    'color',
    'Separators and the frame of a group. Decorative, below 3:1 on purpose.',
  ],
  '--color-border-strong': [
    'color',
    'A frame that has to read as an edge: the outline of a default button.',
  ],
  '--color-border-subtle': ['color', 'The faintest rule, inside a dense group.'],
  '--color-ring': [
    'color',
    'Focus. Drawn as a 1px dotted ring inside the control, around its label. Black, so it clears 3:1 on every surface rowkit paints.',
  ],
  '--color-shadow': ['color', 'Base colour for shadows.'],
  '--color-bevel-highlight': [
    'color',
    'Outer light edge of a raised bevel, inner one of a sunken bevel.',
  ],
  '--color-bevel-light': ['color', 'Inner light edge of a raised bevel.'],
  '--color-bevel-shadow': ['color', 'Inner dark edge of a raised bevel.'],
  '--color-bevel-dark': [
    'color',
    'Outer dark edge of a raised bevel. Being black, it is what gives every control a boundary of well over 3:1 against the face (WCAG 1.4.11).',
  ],
  '--color-titlebar-from': [
    'color',
    'Active title bar, left end of the gradient. The title text sits on this end.',
  ],
  '--color-titlebar-to': ['color', 'Active title bar, right end of the gradient.'],
  '--color-titlebar-inactive-from': ['color', 'Inactive title bar, left end of the gradient.'],
  '--color-titlebar-inactive-to': ['color', 'Inactive title bar, right end of the gradient.'],
  '--color-titlebar-foreground': ['color', 'Active title text.'],
  '--color-titlebar-inactive-foreground': [
    'color',
    "Inactive title text. Black, not Windows 98's silver: silver on the grey gradient is about 2:1 and fails 4.5:1; black is 5.3:1 on `#808080` and 11:1 on `#b5b5b5`.",
  ],
  '--color-neutral-solid': [
    'color',
    'Neutral fill: a solid neutral badge, and anything filled in the neutral colour.',
  ],
  '--color-neutral-solid-hover': ['color', 'Neutral fill under the pointer.'],
  '--color-neutral-on-solid': ['color', 'Text and icons on the neutral fill.'],
  '--color-neutral-subtle': [
    'color',
    'Neutral tint: the face of a subtle neutral badge or callout.',
  ],
  '--color-neutral-on-subtle': ['color', 'Neutral text and icons, on its tint and on the page.'],
  '--color-neutral-border': ['color', 'The edge of a subtle or outlined neutral badge.'],
  '--color-primary-solid': [
    'color',
    'Primary fill — the accent: a solid primary badge, a selected item, the default action in a theme that colours it.',
  ],
  '--color-primary-solid-hover': ['color', 'Primary fill under the pointer.'],
  '--color-primary-on-solid': ['color', 'Text and icons on the primary fill.'],
  '--color-primary-subtle': [
    'color',
    'Primary tint: the face of a subtle primary badge or callout.',
  ],
  '--color-primary-on-subtle': ['color', 'Primary text and icons, on its tint and on the page.'],
  '--color-primary-border': ['color', 'The edge of a subtle or outlined primary badge.'],
  '--color-success-solid': [
    'color',
    'Success fill: a solid success badge, and anything filled in the success colour.',
  ],
  '--color-success-solid-hover': ['color', 'Success fill under the pointer.'],
  '--color-success-on-solid': ['color', 'Text and icons on the success fill.'],
  '--color-success-subtle': [
    'color',
    'Success tint: the face of a subtle success badge or callout.',
  ],
  '--color-success-on-subtle': ['color', 'Success text and icons, on its tint and on the page.'],
  '--color-success-border': ['color', 'The edge of a subtle or outlined success badge.'],
  '--color-warning-solid': [
    'color',
    'Warning fill: a solid warning badge, and anything filled in the warning colour. Yellow carries black, never white: white on `#ffff00` is 1.07:1; its edge is olive, because yellow on silver has almost no edge of its own.',
  ],
  '--color-warning-solid-hover': ['color', 'Warning fill under the pointer.'],
  '--color-warning-on-solid': ['color', 'Text and icons on the warning fill.'],
  '--color-warning-subtle': [
    'color',
    'Warning tint: the face of a subtle warning badge or callout.',
  ],
  '--color-warning-on-subtle': ['color', 'Warning text and icons, on its tint and on the page.'],
  '--color-warning-border': ['color', 'The edge of a subtle or outlined warning badge.'],
  '--color-danger-solid': [
    'color',
    'Danger fill: a solid danger badge, and anything filled in the danger colour.',
  ],
  '--color-danger-solid-hover': ['color', 'Danger fill under the pointer.'],
  '--color-danger-on-solid': ['color', 'Text and icons on the danger fill.'],
  '--color-danger-subtle': ['color', 'Danger tint: the face of a subtle danger badge or callout.'],
  '--color-danger-on-subtle': ['color', 'Danger text and icons, on its tint and on the page.'],
  '--color-danger-border': ['color', 'The edge of a subtle or outlined danger badge.'],
  '--color-control': ['color', "A plain button, a spin or drop button, a table's sort header."],
  '--color-control-foreground': ['color', 'Text and icons on a plain button.'],
  '--color-control-hover': ['color', 'A plain button under the pointer.'],
  '--color-control-active': ['color', 'A plain button while it is held.'],
  '--color-control-primary': ['color', "The default button of a form or dialog — Enter's target."],
  '--color-control-primary-foreground': ['color', 'Text and icons on the default button.'],
  '--color-control-primary-hover': ['color', 'The default button under the pointer.'],
  '--color-control-primary-active': ['color', 'The default button while it is held.'],
  '--color-control-ghost-hover': ['color', 'A flat toolbar button while hovered and while held.'],
  '--color-control-ghost-active': ['color', 'A flat toolbar button while hovered and while held.'],
  '--color-control-latched': ['color', 'The face of a latched toggle, under its pattern.'],
  '--color-control-primary-latched': [
    'color',
    'A latched default button. A toggle is never the default, but if one latches it keeps its colour.',
  ],
  '--color-checked': ['color', 'The box of a checked checkbox or radio, and the mark inside it.'],
  '--color-on-checked': [
    'color',
    'The box of a checked checkbox or radio, and the mark inside it.',
  ],
  '--color-popover': ['color', "A list that drops from a trigger: a select's options."],
  '--color-popover-border': ['color', "A list that drops from a trigger: a select's options."],
  '--color-focus-ring': [
    'color',
    'The ring a theme draws around a focused control, outside its edge.',
  ],
  '--color-caption': [
    'color',
    "A window's caption buttons; one fill per button, for themes that colour them.",
  ],
  '--color-caption-foreground': [
    'color',
    "A window's caption buttons; one fill per button, for themes that colour them.",
  ],
  '--color-caption-close': [
    'color',
    "A window's caption buttons; one fill per button, for themes that colour them.",
  ],
  '--color-caption-minimize': [
    'color',
    "A window's caption buttons; one fill per button, for themes that colour them.",
  ],
  '--color-caption-maximize': [
    'color',
    "A window's caption buttons; one fill per button, for themes that colour them.",
  ],
  '--color-caption-inactive': [
    'color',
    "A window's caption buttons; one fill per button, for themes that colour them.",
  ],
  '--color-table-header': ['color', "A data table's column headers."],
  '--color-table-header-foreground': ['color', "A data table's column headers."],
  '--color-table-stripe': ['color', 'Every other row of a data table. Windows 98 does not stripe.'],
  '--color-table-row-hover': [
    'color',
    'A data table row under the pointer. Windows 98 does not highlight it.',
  ],
  '--color-track': [
    'color',
    'The channel a progress bar or a scroll thumb runs in, and what fills it.',
  ],
  '--color-progress': [
    'color',
    'The channel a progress bar or a scroll thumb runs in, and what fills it.',
  ],
  '--color-scroll-thumb': [
    'color',
    'The channel a progress bar or a scroll thumb runs in, and what fills it.',
  ],
  '--color-scroll-track': ['color', "The channel a scroll bar's thumb runs in, under its pattern."],
  '--color-tooltip-border': ['color', 'The frame of a tooltip.'],
  '--color-groupbox': [
    'color',
    "The inside of a group box's frame, and the face around it — behind the legend and the frame's edge. Both the window's silver in Windows 98.",
  ],
  '--color-groupbox-face': [
    'color',
    "The inside of a group box's frame, and the face around it — behind the legend and the frame's edge. Both the window's silver in Windows 98.",
  ],
  '--color-toast-close': [
    'color',
    "A toast's ✕: the caption button's silver in Windows 98, a soft grey disc elsewhere.",
  ],
  '--color-toast-close-foreground': [
    'color',
    "A toast's ✕: the caption button's silver in Windows 98, a soft grey disc elsewhere.",
  ],
  '--color-loading-foreground': [
    'color',
    '«Loading…» in a dropped list: plain text in Windows 98, the subtle grey elsewhere.',
  ],
  '--color-select-search': [
    'color',
    "The strip that holds a searchable list's search box: the window face in Windows 98, nothing elsewhere.",
  ],
  '--color-pager': [
    'color',
    "A pager's buttons: raised command buttons in Windows 98, flat elsewhere.",
  ],
  '--color-pager-hover': [
    'color',
    "A pager's buttons: raised command buttons in Windows 98, flat elsewhere.",
  ],
  '--color-pager-active': [
    'color',
    "A pager's buttons: raised command buttons in Windows 98, flat elsewhere.",
  ],
  '--color-filter-bar': ['color', 'The strip a filter bar sits on.'],
  '--color-chip': ['color', 'A filter chip: its face, its edge and its text.'],
  '--color-chip-border': ['color', 'A filter chip: its face, its edge and its text.'],
  '--color-chip-foreground': ['color', 'A filter chip: its face, its edge and its text.'],
  '--color-chip-remove': [
    'color',
    "The face of a chip's ✕ at rest: the chip's own white in Windows 98.",
  ],
  '--color-field-highlight': [
    'color',
    "The value of a read-only field that holds focus — a drop-down list's — highlighted the way Windows 98 marks it, and the text on it.",
  ],
  '--color-on-field-highlight': [
    'color',
    "The value of a read-only field that holds focus — a drop-down list's — highlighted the way Windows 98 marks it, and the text on it.",
  ],
  '--color-field-caret': ['color', 'The text caret in a field.'],
  '--color-field-button': [
    'color',
    "The buttons inside a field: a select's drop button, a number's spin buttons.",
  ],
  '--rk-shadow-none': ['shadow', 'No bevel.'],
  '--rk-shadow-raised': ['shadow', 'Buttons and raised panels.'],
  '--rk-shadow-window': [
    'shadow',
    "A window's frame: like `raised`, with the bright white on the inner edge.",
  ],
  '--rk-shadow-raised-default': [
    'shadow',
    "The default button of a dialog: a 1px black frame around a raised bevel, so Enter's target is visible before anyone presses it.",
  ],
  '--rk-shadow-pressed': ['shadow', 'A button held down, or a toggle that is on.'],
  '--rk-shadow-sunken': [
    'shadow',
    'Text fields, lists and table bodies: the white well a value sits in.',
  ],
  '--rk-shadow-status': ['shadow', 'A thin sunken edge: status-bar sections, counters, Badge.'],
  '--rk-shadow-etched': ['shadow', 'An etched groove: group boxes and separators.'],
  '--rk-shadow-raised-thin': ['shadow', 'A thin raised edge: a flat toolbar button while hovered.'],
  '--rk-shadow-popover': [
    'shadow',
    'A list dropped from a trigger. Windows 98 frames it with a border, not a shadow.',
  ],
  '--rk-shadow-table': ['shadow', "A data table's frame: the sunken well its rows sit in."],
  '--rk-shadow-header': ['shadow', "A data table's column header: a raised button."],
  '--rk-shadow-caption': ['shadow', "A window's caption button."],
  '--rk-shadow-statusbar': ['shadow', 'The strip of a status bar, behind its sections.'],
  '--rk-shadow-titlebar': ['shadow', 'The edge between a title bar and the window under it.'],
  '--rk-shadow-checked': [
    'shadow',
    'A checked check box: the same sunken well as an unchecked one, in Windows 98.',
  ],
  '--rk-shadow-field-button-pressed': [
    'shadow',
    'A button inside a field while held, or while its list is open: pressed in, in Windows 98.',
  ],
  '--rk-shadow-latched-ghost': [
    'shadow',
    'A flat toolbar button that is latched on: pressed in, in Windows 98.',
  ],
  '--rk-shadow-checked-selected': [
    'shadow',
    'A checked check box in a selected table row: its usual well, in Windows 98.',
  ],
  '--rk-shadow-toast-close': ['shadow', "A toast's ✕: a caption button, raised, in Windows 98."],
  '--rk-shadow-pager': [
    'shadow',
    "A pager's buttons: a raised command button, its focused frame, and pressed in while held or while it is the current page. Flat in a theme that draws the pager as a row of plain numbers.",
  ],
  '--rk-shadow-pager-focus': [
    'shadow',
    "A pager's buttons: a raised command button, its focused frame, and pressed in while held or while it is the current page. Flat in a theme that draws the pager as a row of plain numbers.",
  ],
  '--rk-shadow-pager-pressed': [
    'shadow',
    "A pager's buttons: a raised command button, its focused frame, and pressed in while held or while it is the current page. Flat in a theme that draws the pager as a row of plain numbers.",
  ],
  '--rk-shadow-field-button': ['shadow', 'A button inside a field: raised, in Windows 98.'],
  '--rk-shadow-scroll-thumb': ['shadow', "A scroll bar's thumb."],
  '--rk-shadow-scroll-x': [
    'shadow',
    'The edge of a sticky table column while rows scroll under it.',
  ],
  '--rk-shadow-sticky-header': [
    'shadow',
    'The rule under a sticky table header, drawn as a shadow rather than a border.',
  ],
  '--spacing-control-xs': [
    'size',
    "Control heights: buttons, fields, selects. Also the side of a square icon button's row.",
  ],
  '--spacing-control-sm': [
    'size',
    "Control heights: buttons, fields, selects. Also the side of a square icon button's row.",
  ],
  '--spacing-control-md': [
    'size',
    "Control heights: buttons, fields, selects. Also the side of a square icon button's row.",
  ],
  '--spacing-control-lg': [
    'size',
    "Control heights: buttons, fields, selects. Also the side of a square icon button's row.",
  ],
  '--spacing-icon-xs': [
    'size',
    'Square icon buttons. A touch wider than the row they sit in, as Windows 98 drew them.',
  ],
  '--spacing-icon-sm': [
    'size',
    'Square icon buttons. A touch wider than the row they sit in, as Windows 98 drew them.',
  ],
  '--spacing-icon-md': [
    'size',
    'Square icon buttons. A touch wider than the row they sit in, as Windows 98 drew them.',
  ],
  '--spacing-icon-lg': [
    'size',
    'Square icon buttons. A touch wider than the row they sit in, as Windows 98 drew them.',
  ],
  '--spacing-button-min-xs': [
    'size',
    "A button's minimum width, so a short label still makes a button worth aiming at.",
  ],
  '--spacing-button-min-sm': [
    'size',
    "A button's minimum width, so a short label still makes a button worth aiming at.",
  ],
  '--spacing-button-min-md': [
    'size',
    "A button's minimum width, so a short label still makes a button worth aiming at.",
  ],
  '--spacing-button-min-lg': [
    'size',
    "A button's minimum width, so a short label still makes a button worth aiming at.",
  ],
  '--spacing-button-px-xs': ['size', "A button's side padding."],
  '--spacing-button-px-sm': ['size', "A button's side padding."],
  '--spacing-button-px-md': ['size', "A button's side padding."],
  '--spacing-button-px-lg': ['size', "A button's side padding."],
  '--spacing-field-px': ['size', "A field's side padding, inside its edge."],
  '--spacing-field-px-lg': ['size', "A field's side padding, inside its edge."],
  '--spacing-field-gap-sm': [
    'size',
    "A field's spacing: between label, control and message at each size, between a label and the control beside it, and between the error icon and its text.",
  ],
  '--spacing-field-gap-md': [
    'size',
    "A field's spacing: between label, control and message at each size, between a label and the control beside it, and between the error icon and its text.",
  ],
  '--spacing-field-gap-lg': [
    'size',
    "A field's spacing: between label, control and message at each size, between a label and the control beside it, and between the error icon and its text.",
  ],
  '--spacing-field-left-gap': [
    'size',
    "A field's spacing: between label, control and message at each size, between a label and the control beside it, and between the error icon and its text.",
  ],
  '--spacing-field-error-gap': [
    'size',
    "A field's spacing: between label, control and message at each size, between a label and the control beside it, and between the error icon and its text.",
  ],
  '--spacing-check': ['size', "The side of a checkbox's box, and of an option button."],
  '--spacing-radio': ['size', "The side of a checkbox's box, and of an option button."],
  '--spacing-check-gap': [
    'size',
    "Between a check box or option button and its label, and the label's own inset (where the dotted ring sits).",
  ],
  '--spacing-check-label-px': [
    'size',
    "Between a check box or option button and its label, and the label's own inset (where the dotted ring sits).",
  ],
  '--spacing-titlebar': ['size', "A window's or a dialog's title bar."],
  '--spacing-caption-w': ['size', 'A caption button: minimise, maximise, close.'],
  '--spacing-caption-h': ['size', 'A caption button: minimise, maximise, close.'],
  '--spacing-caption-gap': [
    'size',
    'The gap between caption buttons, and the extra space before the close button.',
  ],
  '--spacing-caption-close-gap': [
    'size',
    'The gap between caption buttons, and the extra space before the close button.',
  ],
  '--spacing-titlebar-px': ['size', "A title bar's side padding."],
  '--spacing-title-inset-start': [
    'size',
    "Where a dialog's title starts and ends in its title bar, clear of the close button. Equal values centre it.",
  ],
  '--spacing-title-inset-end': [
    'size',
    "Where a dialog's title starts and ends in its title bar, clear of the close button. Equal values centre it.",
  ],
  '--spacing-frame': [
    'size',
    "The frame between a window's edge and its content: the width of the bevel. A theme whose windows have no bevel sets it to zero.",
  ],
  '--spacing-dialog-px': [
    'size',
    "A dialog's insets: the side padding of its header, body and footer, the room above the first line, and above and below the footer's buttons.",
  ],
  '--spacing-dialog-pt': [
    'size',
    "A dialog's insets: the side padding of its header, body and footer, the room above the first line, and above and below the footer's buttons.",
  ],
  '--spacing-dialog-footer-pt': [
    'size',
    "A dialog's insets: the side padding of its header, body and footer, the room above the first line, and above and below the footer's buttons.",
  ],
  '--spacing-dialog-footer-pb': [
    'size',
    "A dialog's insets: the side padding of its header, body and footer, the room above the first line, and above and below the footer's buttons.",
  ],
  '--spacing-item': ['size', "One option in a list: a select's, a menu's."],
  '--spacing-item-pl': [
    'size',
    "An option's padding either side, the column its check mark sits in, the gap after it, and the mark.",
  ],
  '--spacing-item-pr': [
    'size',
    "An option's padding either side, the column its check mark sits in, the gap after it, and the mark.",
  ],
  '--spacing-item-check': [
    'size',
    "An option's padding either side, the column its check mark sits in, the gap after it, and the mark.",
  ],
  '--spacing-item-gap': [
    'size',
    "An option's padding either side, the column its check mark sits in, the gap after it, and the mark.",
  ],
  '--spacing-item-check-glyph': [
    'size',
    "An option's padding either side, the column its check mark sits in, the gap after it, and the mark.",
  ],
  '--spacing-popover-inset': [
    'size',
    "The inset around a dropped list's options, inside its border: 1px in Windows 98, as Figma draws it.",
  ],
  '--spacing-table-header-px': [
    'size',
    "A data table's side padding: a header cell's, around the 1px its label's focus ring takes, and a body cell's.",
  ],
  '--spacing-table-cell-px': [
    'size',
    "A data table's side padding: a header cell's, around the 1px its label's focus ring takes, and a body cell's.",
  ],
  '--spacing-row-sm': ['size', 'Data table rows, and the header that matches them.'],
  '--spacing-row-md': ['size', 'Data table rows, and the header that matches them.'],
  '--spacing-select-arrow': [
    'size',
    "A select's drop arrows, and how far the down arrow tucks under an up arrow above it.",
  ],
  '--spacing-select-arrow-overlap': [
    'size',
    "A select's drop arrows, and how far the down arrow tucks under an up arrow above it.",
  ],
  '--spacing-select-message-px': [
    'size',
    '«Loading…» and «No results found» in a dropped list: padding, and the gap after the busy glyph.',
  ],
  '--spacing-select-message-py': [
    'size',
    '«Loading…» and «No results found» in a dropped list: padding, and the gap after the busy glyph.',
  ],
  '--spacing-select-message-gap': [
    'size',
    '«Loading…» and «No results found» in a dropped list: padding, and the gap after the busy glyph.',
  ],
  '--spacing-select-search-p': [
    'size',
    "The strip around a searchable list's search box, and the space under it.",
  ],
  '--spacing-select-search-gap': [
    'size',
    "The strip around a searchable list's search box, and the space under it.",
  ],
  '--spacing-field-button-h-sm': [
    'size',
    "The buttons inside a number, date or select field: their height at each size, centred in the field as Figma draws them; how far they sit from the field's right edge; and the date field's glyph. A select's arrows sit `select-pr` in.",
  ],
  '--spacing-field-button-h': [
    'size',
    "The buttons inside a number, date or select field: their height at each size, centred in the field as Figma draws them; how far they sit from the field's right edge; and the date field's glyph. A select's arrows sit `select-pr` in.",
  ],
  '--spacing-field-button-h-lg': [
    'size',
    "The buttons inside a number, date or select field: their height at each size, centred in the field as Figma draws them; how far they sit from the field's right edge; and the date field's glyph. A select's arrows sit `select-pr` in.",
  ],
  '--spacing-field-button-pr': [
    'size',
    "The buttons inside a number, date or select field: their height at each size, centred in the field as Figma draws them; how far they sit from the field's right edge; and the date field's glyph. A select's arrows sit `select-pr` in.",
  ],
  '--spacing-field-drop-icon': [
    'size',
    "The buttons inside a number, date or select field: their height at each size, centred in the field as Figma draws them; how far they sit from the field's right edge; and the date field's glyph. A select's arrows sit `select-pr` in.",
  ],
  '--spacing-select-pr': [
    'size',
    "The buttons inside a number, date or select field: their height at each size, centred in the field as Figma draws them; how far they sit from the field's right edge; and the date field's glyph. A select's arrows sit `select-pr` in.",
  ],
  '--spacing-filter-bar-p': ['size', "A filter bar's padding and the space between its items."],
  '--spacing-filter-bar-gap': ['size', "A filter bar's padding and the space between its items."],
  '--spacing-chip-px': [
    'size',
    "A filter chip's side padding, and its right padding beside the ✕.",
  ],
  '--spacing-chip-pr-remove': [
    'size',
    "A filter chip's side padding, and its right padding beside the ✕.",
  ],
  '--spacing-toast-py': [
    'size',
    "A toast's padding, the gap between its icon, text and ✕, and between its lines.",
  ],
  '--spacing-toast-pl': [
    'size',
    "A toast's padding, the gap between its icon, text and ✕, and between its lines.",
  ],
  '--spacing-toast-pr': [
    'size',
    "A toast's padding, the gap between its icon, text and ✕, and between its lines.",
  ],
  '--spacing-toast-gap': [
    'size',
    "A toast's padding, the gap between its icon, text and ✕, and between its lines.",
  ],
  '--spacing-toast-body-gap': [
    'size',
    "A toast's padding, the gap between its icon, text and ✕, and between its lines.",
  ],
  '--spacing-toast-icon': ['size', "A toast's status icon, and its ✕."],
  '--spacing-toast-close-w': ['size', "A toast's status icon, and its ✕."],
  '--spacing-toast-close-h': ['size', "A toast's status icon, and its ✕."],
  '--spacing-pager-px': ['size', "A page number's side padding."],
  '--spacing-pager-arrow': [
    'size',
    "A pager's arrows, the inset of the dotted focus ring round a page label, and how narrow a small page button may get (Windows 98 lets it hug its number; a theme can keep it square).",
  ],
  '--spacing-pager-focus-px': [
    'size',
    "A pager's arrows, the inset of the dotted focus ring round a page label, and how narrow a small page button may get (Windows 98 lets it hug its number; a theme can keep it square).",
  ],
  '--spacing-pager-min-sm': [
    'size',
    "A pager's arrows, the inset of the dotted focus ring round a page label, and how narrow a small page button may get (Windows 98 lets it hug its number; a theme can keep it square).",
  ],
  '--spacing-chip-sm': ['size', 'A filter chip.'],
  '--spacing-chip-md': ['size', 'A filter chip.'],
  '--spacing-badge-px-sm': ['size', "A badge's side padding."],
  '--spacing-badge-px-md': ['size', "A badge's side padding."],
  '--spacing-badge-dot': ['size', "The side of a badge's status dot."],
  '--spacing-empty-p-sm': [
    'size',
    "An empty view's padding at each size, and the gap between its icon and its text at `md` and `lg`.",
  ],
  '--spacing-empty-p-md': [
    'size',
    "An empty view's padding at each size, and the gap between its icon and its text at `md` and `lg`.",
  ],
  '--spacing-empty-p-lg': [
    'size',
    "An empty view's padding at each size, and the gap between its icon and its text at `md` and `lg`.",
  ],
  '--spacing-empty-gap': [
    'size',
    "An empty view's padding at each size, and the gap between its icon and its text at `md` and `lg`.",
  ],
  '--spacing-tooltip-px': ['size', "A tooltip's padding."],
  '--spacing-tooltip-py': ['size', "A tooltip's padding."],
  '--spacing-statusbar': ['size', 'A status bar.'],
  '--spacing-statusbar-px': [
    'size',
    "A status bar's padding and the space between its sections; a section's side padding and the space inside it.",
  ],
  '--spacing-statusbar-py': [
    'size',
    "A status bar's padding and the space between its sections; a section's side padding and the space inside it.",
  ],
  '--spacing-statusbar-gap': [
    'size',
    "A status bar's padding and the space between its sections; a section's side padding and the space inside it.",
  ],
  '--spacing-statusbar-section-px': [
    'size',
    "A status bar's padding and the space between its sections; a section's side padding and the space inside it.",
  ],
  '--spacing-statusbar-section-gap': [
    'size',
    "A status bar's padding and the space between its sections; a section's side padding and the space inside it.",
  ],
  '--spacing-progress': [
    'size',
    'A progress bar: its height, the inset around the fill, and the fill.',
  ],
  '--spacing-progress-inset': [
    'size',
    'A progress bar: its height, the inset around the fill, and the fill.',
  ],
  '--spacing-progress-fill': [
    'size',
    'A progress bar: its height, the inset around the fill, and the fill.',
  ],
  '--spacing-progress-block': [
    'size',
    'One block of the fill, and the block plus the gap after it. Equal values draw a solid bar.',
  ],
  '--spacing-progress-period': [
    'size',
    'One block of the fill, and the block plus the gap after it. Equal values draw a solid bar.',
  ],
  '--spacing-progress-segment': [
    'size',
    'The segment an indeterminate bar moves along the track: four blocks in Windows 98.',
  ],
  '--spacing-scrollbar': [
    'size',
    "A scroll bar's thickness, and the side of its arrow buttons (zero hides them).",
  ],
  '--spacing-scroll-button': [
    'size',
    "A scroll bar's thickness, and the side of its arrow buttons (zero hides them).",
  ],
  '--spacing-scroll-inset': ['size', 'The space between the thumb and the edge of its track.'],
  '--spacing-groupbox-top': [
    'size',
    "A group box: where its frame starts, the room above its content, and its legend's offset.",
  ],
  '--spacing-groupbox-pt': [
    'size',
    "A group box: where its frame starts, the room above its content, and its legend's offset.",
  ],
  '--spacing-groupbox-legend-x': [
    'size',
    "A group box: where its frame starts, the room above its content, and its legend's offset.",
  ],
  '--spacing-groupbox-legend-px': [
    'size',
    "A group box: where its frame starts, the room above its content, and its legend's offset.",
  ],
  '--radius-none': [
    'radius',
    'Always square, whatever `--radius` is: table cells, anything that tiles.',
  ],
  '--radius-xs': ['radius', 'Checkboxes and tags inside a cell.'],
  '--radius-sm': ['radius', 'Badges and small controls.'],
  '--radius-md': ['radius', 'Buttons, inputs and panels.'],
  '--radius-lg': ['radius', 'Windows, dialogs and popovers.'],
  '--radius-xl': ['radius', 'Large empty-state panels.'],
  '--radius-full': [
    'radius',
    'Circle. The only rounded shape Windows 98 draws: radio buttons, and a round skeleton.',
  ],
  '--radius-pill': [
    'radius',
    'A capsule, where the theme draws one: a chip, a progress bar, a caption button. Square in Windows 98, whatever `--radius` is.',
  ],
  '--rk-focus-label-width': [
    'style',
    "The ring drawn around a control's label, inside it. Windows 98's dotted rectangle.",
  ],
  '--rk-focus-ring-width': [
    'style',
    'The ring drawn on the focused element itself — a row, a scrolling region, a toast.',
  ],
  '--rk-focus-ring-style': [
    'style',
    'The ring drawn on the focused element itself — a row, a scrolling region, a toast.',
  ],
  '--rk-focus-outer-width': [
    'style',
    "The ring drawn around a control's edge, outside it. Windows 98 has none.",
  ],
  '--rk-focus-outer-offset': [
    'style',
    "The ring drawn around a control's edge, outside it. Windows 98 has none.",
  ],
  '--rk-press-shift': ['style', "How far a held button's label moves down and right."],
  '--rk-press-brightness': [
    'style',
    'A brightness filter on a held caption button. `1` leaves it alone.',
  ],
  '--rk-dither-image': ['style', 'The pattern over a latched toggle and a scroll track.'],
  '--rk-loading-image': ['style', 'The pattern of a loading placeholder, and how it moves.'],
  '--rk-animate-loading': ['style', 'The pattern of a loading placeholder, and how it moves.'],
  '--rk-animate-busy': [
    'style',
    "The busy mark in a loading button: Windows 98's hourglass stands still; a theme with a spinner glyph turns it.",
  ],
  '--rk-animate-progress': [
    'style',
    "An indeterminate progress bar's segment travelling across the track. Windows 98 moves its four blocks one block every 100ms and starts again at the left; `ProgressBar` sets `--rk-progress-steps` to the number of steps that fit the track it measures.",
  ],
  '--rk-duration-control': [
    'style',
    'How long a control takes to change state. Windows 98 changes instantly.',
  ],
  '--rk-animate-overlay-in': ['style', 'How a dialog, a list or a toast arrives.'],
  '--rk-etch-width': [
    'style',
    'The light second line of an etched separator. Zero leaves a single line.',
  ],
  '--rk-caption-order': [
    'style',
    'Where the caption buttons sit in the title bar: `0` after the title, `-1` before it.',
  ],
  '--rk-close-order': ['style', 'Where the close button sits among them: `0` last, `-1` first.'],
  '--rk-titlebar-icon': [
    'style',
    'Whether a window shows its icon in the title bar: `flex`, or `none`.',
  ],
  '--rk-titlebar-align': ['style', 'Where the title sits: `start`, or `center`.'],
  '--rk-titlebar-balance': [
    'style',
    'Space kept clear opposite the caption buttons, so a centred title is centred on the bar.',
  ],
  '--rk-caption-glyph-opacity': [
    'style',
    "The opacity of a caption button's glyph at rest; hovering the title bar shows it.",
  ],
  '--rk-legend-weight': ['style', "The weight of a group box's legend."],
  '--rk-link-decoration': ['style', 'The line under a link-styled button: `underline`, or `none`.'],
  '--rk-invalid-width': [
    'style',
    'The red frame inside an invalid field. Windows 98 marks it with the error icon only.',
  ],
  '--rk-field-error-align': [
    'style',
    "Where a field's error icon sits beside a message that wraps: `center`, or `start`.",
  ],
  '--rk-select-up': [
    'style',
    "Whether a select's drop button shows an up arrow over its down arrow: `block`, or `none`.",
  ],
  '--rk-footer-direction': [
    'style',
    "The order of a dialog footer's buttons, written primary first: `row` keeps it, as Windows 98 does; `row-reverse` puts the primary button last.",
  ],
  '--rk-empty-direction': [
    'style',
    'How an empty view lays out its icon and text: `row` puts the icon beside the text, `column` above it; `start` or `center` aligns the text.',
  ],
  '--rk-empty-align': [
    'style',
    'How an empty view lays out its icon and text: `row` puts the icon beside the text, `column` above it; `start` or `center` aligns the text.',
  ],
  '--rk-overlay-bg': ['style', 'What a modal dialog lays over the page behind it.'],
  '--rk-popover-backdrop': ['style', 'A backdrop filter behind a dropped list.'],
  '--rk-popover-border-width': [
    'style',
    "A dropped list's border. Windows 98 draws a black line; a theme that rings the list in its shadow (`--rk-shadow-popover`) sets it to zero.",
  ],
  '--rk-scrollbar-buttons': [
    'style',
    'Whether a scroll bar has arrow buttons: `block`, or `none`.',
  ],
  '--rk-glyph-scale': [
    'style',
    'A multiplier on small glyphs — a check mark, a caption glyph — for a theme whose glyphs are not pixel art.',
  ],
  '--rk-radio-fill': [
    'style',
    "An option button drawn by CSS rather than by its pixels: how much of the well and the dot to paint (`0%` paints neither), the dot's radius and the edge's width.",
  ],
  '--rk-radio-dot-r': [
    'style',
    "An option button drawn by CSS rather than by its pixels: how much of the well and the dot to paint (`0%` paints neither), the dot's radius and the edge's width.",
  ],
  '--rk-radio-edge': [
    'style',
    "An option button drawn by CSS rather than by its pixels: how much of the well and the dot to paint (`0%` paints neither), the dot's radius and the edge's width.",
  ],
  '--rk-icon-pixels': ['style', "`display` of a pixel icon's pixels."],
  '--rk-icon-glyphs': [
    'style',
    'Whether the glyphs mask the icons at all. `initial` makes every glyph mask invalid, so a Windows 98 icon has no mask and nothing of it is clipped; an empty value lets them through. It is prepended to each mask image.',
  ],
  '--rk-icon-fill': [
    'style',
    "The fill a theme's own glyph is painted in; transparent draws nothing.",
  ],
  '--rk-icon-tone-danger': [
    'style',
    'The fills of the glyphs that keep a colour: status icons and folders. Transparent in Windows 98, whose pixel icons carry their own colours.',
  ],
  '--rk-icon-tone-warning': [
    'style',
    'The fills of the glyphs that keep a colour: status icons and folders. Transparent in Windows 98, whose pixel icons carry their own colours.',
  ],
  '--rk-icon-tone-info': [
    'style',
    'The fills of the glyphs that keep a colour: status icons and folders. Transparent in Windows 98, whose pixel icons carry their own colours.',
  ],
  '--rk-icon-tone-success': [
    'style',
    'The fills of the glyphs that keep a colour: status icons and folders. Transparent in Windows 98, whose pixel icons carry their own colours.',
  ],
  '--rk-icon-tone-folder': [
    'style',
    'The fills of the glyphs that keep a colour: status icons and folders. Transparent in Windows 98, whose pixel icons carry their own colours.',
  ],
  '--font-sans': ['font', 'UI and body text.'],
  '--font-mono': ['font', 'Code, IDs and numbers that must align in a column.'],
  '--text-ui': [
    'font',
    '13/16 — every control, label, menu and table cell. Bold for titles and the default button.',
  ],
  '--text-heading': ['font', '16/20, bold — the heading of an empty state or a group.'],
  '--text-mono': [
    'font',
    "16/16 — the fixed-width face beside interface text. VT323's x-height is 0.4em to PT Sans's 0.5em, so 16px VT323 stands exactly as tall as 13px PT Sans.",
  ],
  '--text-doc': ['font', '16/26 — documentation paragraphs, about seventy characters to a line.'],
  '--text-doc-mono': [
    'font',
    '20/20 — code beside documentation text: as tall as 16px PT Sans, for the same reason as `mono`.',
  ],
  '--text-doc-h1': ['font', '26/30, bold — a documentation page title.'],
  '--text-doc-h2': ['font', '19/24, bold — a documentation section.'],
  '--text-doc-h3': ['font', '15/20, bold — a documentation subsection.'],
  '--font-weight-normal': ['font', 'Body text.'],
  '--font-weight-bold': ['font', 'Window titles, headings, the default button.'],
  '--font-weight-strong': [
    'font',
    "The weight a theme gives emphasis: titles, headings, a table's totals. Components use this rather than `bold`, so a theme can make emphasis semibold without changing what `font-bold` means in the app around it.",
  ],
}
