import { inject, provide, type InjectionKey, type Ref } from 'vue'

/**
 * What a `Field` tells the control inside it.
 *
 * The ids are generated by `Field` and consumed by the control so that
 * `aria-describedby` points at the hint and error that are actually rendered.
 * Wiring this by hand is the single most commonly skipped part of an
 * accessible form, which is why it is not left to the consumer.
 */
export interface FieldContext {
  /** Id for the control itself; the label's `for` target. */
  readonly controlId: Ref<string>
  /**
   * Space-separated ids of the descriptions currently rendered, or `undefined`
   * when there are none. Goes straight onto the control's `aria-describedby`.
   */
  readonly describedBy: Ref<string | undefined>
  /** Whether the field is reporting a validation error. */
  readonly invalid: Ref<boolean>
  /** Whether the control should render and behave as disabled. */
  readonly disabled: Ref<boolean>
  /** Whether the control is required. */
  readonly required: Ref<boolean>
}

export const FIELD_CONTEXT: InjectionKey<FieldContext> = Symbol('rowkit.field')

export function provideFieldContext(context: FieldContext): void {
  provide(FIELD_CONTEXT, context)
}

/**
 * Reads the surrounding `Field`, if there is one.
 *
 * Controls stay usable on their own — a bare `Input` outside a `Field` is a
 * legitimate thing to render in a toolbar or a table cell — so this returns
 * `undefined` rather than throwing.
 */
export function useFieldContext(): FieldContext | undefined {
  return inject(FIELD_CONTEXT, undefined)
}
