/**
 * Sample people for the larger DataTable examples. Generated by index rather
 * than at random, so every render — server and browser — shows the same rows.
 * In an application these come from your API.
 */
export interface Person {
  id: number
  name: string
  email: string
  role: 'Owner' | 'Admin' | 'Member' | 'Billing'
  team: string
  status: 'active' | 'invited' | 'suspended'
  seats: number
  joined: string
}

const first = ['Ada', 'Grace', 'Alan', 'Katherine', 'Barbara', 'Edsger', 'Margaret', 'Donald']
const last = ['Lovelace', 'Hopper', 'Turing', 'Johnson', 'Liskov', 'Dijkstra', 'Hamilton', 'Knuth']
const roles = ['Owner', 'Admin', 'Member', 'Billing'] as const
const teams = ['Platform', 'Design', 'Finance', 'Support', 'Research']
const statuses = ['active', 'invited', 'suspended'] as const

export const people: Person[] = Array.from({ length: 48 }, (_, i) => {
  const given = first[i % first.length] ?? ''
  const family = last[(i * 3) % last.length] ?? ''
  return {
    id: i + 1,
    name: `${given} ${family}`,
    email: `${given.toLowerCase()}.${family.toLowerCase()}${String(i)}@example.com`,
    role: roles[i % roles.length] ?? 'Member',
    team: teams[(i * 2) % teams.length] ?? '',
    status: statuses[i % statuses.length] ?? 'active',
    seats: (i * 7) % 24,
    joined: `2026-${String((i % 9) + 1).padStart(2, '0')}-${String((i % 27) + 1).padStart(2, '0')}`,
  }
})
