import type { SemanticColorName } from '../color'
import type { RadiusName } from '../radius'
import type { ShadowName } from '../shadow'
import type { SizeName } from '../size'
import type { StyleName } from '../style'

/**
 * The modern theme: the look of a current desktop operating system. White and
 * light-grey surfaces, a blue accent, rounded corners, soft shadows, a ring
 * around the focused control and short transitions. Light and dark.
 *
 * Switched on with `data-theme="modern"` on any element, `<html>` included.
 * The colour scheme follows the system unless `data-color-scheme="light"` or
 * `"dark"` on the same element fixes it.
 *
 * DRAFT. These values are assembled from platform guidelines so the theme can
 * be built and reviewed in code; the Figma file supersedes them value for
 * value once the designer has drawn it.
 */

/** The modern palette. Eight-digit values carry alpha. */
export const modernPalette = {
  white: '#ffffff',
  black: '#000000',
  transparent: '#00000000',

  'gray-50': '#f9f9fb',
  'gray-100': '#f5f5f7',
  'gray-150': '#efeff2',
  'gray-200': '#e8e8ed',
  'gray-250': '#e0e0e5',
  'gray-300': '#d2d2d7',
  'gray-400': '#aeaeb2',
  'gray-500': '#86868b',
  'gray-600': '#6e6e73',
  'gray-700': '#515154',
  'gray-750': '#48484a',
  'gray-800': '#3a3a3c',
  'gray-850': '#2c2c2e',
  'gray-900': '#1d1d1f',
  'gray-925': '#1c1c1e',
  'gray-950': '#161617',

  blue: '#0071e3',
  'blue-hover': '#0068d6',
  'blue-active': '#0062c4',
  'blue-link': '#0066cc',
  'blue-link-dark': '#2997ff',
  'blue-subtle': '#e8f1fc',
  'blue-subtle-dark': '#0f2a47',
  'blue-text': '#0058b0',
  'blue-text-dark': '#6cb4ff',
  'blue-border': '#b3d1f5',
  'blue-border-dark': '#1f4b7a',
  'blue-ring': '#0071e3cc',
  'blue-ring-dark': '#2997ffcc',

  green: '#1f7a35',
  'green-hover': '#1a6a2e',
  'green-subtle': '#e7f6eb',
  'green-subtle-dark': '#12301b',
  'green-text': '#1b6e31',
  'green-text-dark': '#5fd47e',
  'green-border': '#b4e2c0',
  'green-border-dark': '#245c33',

  orange: '#ff9f0a',
  'orange-hover': '#f59300',
  'orange-subtle': '#fff4e0',
  'orange-subtle-dark': '#3a2a0c',
  'orange-text': '#8a4b00',
  'orange-text-dark': '#ffbe5c',
  'orange-border': '#ffd59a',
  'orange-border-dark': '#6b4a12',

  red: '#d70015',
  'red-hover': '#c00013',
  'red-subtle': '#fdeaea',
  'red-subtle-dark': '#3d1416',
  'red-text': '#b0000f',
  'red-text-dark': '#ffa0a4',
  'red-border': '#f5b5b9',
  'red-border-dark': '#7a2329',

  'traffic-red': '#ff5f57',
  'traffic-yellow': '#febc2e',
  'traffic-green': '#28c840',

  'ink-4': '#0000000a',
  'ink-6': '#0000000f',
  'ink-8': '#00000014',
  'ink-10': '#0000001a',
  'ink-12': '#0000001f',
  'ink-15': '#00000026',
  'ink-25': '#00000040',
  'ink-50': '#00000080',
  'light-4': '#ffffff0a',
  'light-8': '#ffffff14',
  'light-12': '#ffffff1f',
  'light-16': '#ffffff29',
  'light-25': '#ffffff40',
  'light-50': '#ffffff80',

  'glass-light': '#ffffffd9',
  'glass-dark': '#323234e0',
  'desktop-light': '#c7d3e6',
  'desktop-dark': '#101014',
} as const

export type ModernPaletteName = keyof typeof modernPalette

const p = (name: ModernPaletteName) => `var(--color-modern-${name})` as const

/** Semantic colours, light. Every semantic token is listed: the theme leaves nothing to Windows 98. */
export const modernLightColor: Record<SemanticColorName, string> = {
  background: p('gray-100'),
  desktop: p('desktop-light'),
  card: p('white'),
  muted: p('gray-100'),
  accent: p('ink-4'),
  'surface-active': p('gray-200'),
  'surface-selected': p('blue'),
  'surface-disabled': p('gray-100'),
  skeleton: p('gray-200'),
  input: p('white'),
  'tooltip-bg': p('gray-100'),

  foreground: p('gray-900'),
  'muted-foreground': p('gray-700'),
  'text-subtle': p('gray-600'),
  'text-disabled': p('gray-400'),
  'text-disabled-emboss': p('transparent'),
  'on-selected': p('white'),
  link: p('blue-link'),

  border: p('gray-300'),
  'border-strong': p('gray-500'),
  'border-subtle': p('gray-200'),
  ring: p('blue'),
  shadow: p('black'),
  'bevel-highlight': p('transparent'),
  'bevel-light': p('gray-300'),
  'bevel-shadow': p('gray-300'),
  'bevel-dark': p('gray-500'),

  'titlebar-from': p('gray-50'),
  'titlebar-to': p('gray-50'),
  'titlebar-inactive-from': p('gray-100'),
  'titlebar-inactive-to': p('gray-100'),
  'titlebar-foreground': p('gray-900'),
  'titlebar-inactive-foreground': p('gray-600'),

  'neutral-solid': p('gray-600'),
  'neutral-solid-hover': p('gray-700'),
  'neutral-on-solid': p('white'),
  'neutral-subtle': p('gray-100'),
  'neutral-on-subtle': p('gray-800'),
  'neutral-border': p('gray-300'),

  'primary-solid': p('blue'),
  'primary-solid-hover': p('blue-active'),
  'primary-on-solid': p('white'),
  'primary-subtle': p('blue-subtle'),
  'primary-on-subtle': p('blue-text'),
  'primary-border': p('blue-border'),

  'success-solid': p('green'),
  'success-solid-hover': p('green-hover'),
  'success-on-solid': p('white'),
  'success-subtle': p('green-subtle'),
  'success-on-subtle': p('green-text'),
  'success-border': p('green-border'),

  'warning-solid': p('orange'),
  'warning-solid-hover': p('orange-hover'),
  'warning-on-solid': p('gray-900'),
  'warning-subtle': p('orange-subtle'),
  'warning-on-subtle': p('orange-text'),
  'warning-border': p('orange-border'),

  'danger-solid': p('red'),
  'danger-solid-hover': p('red-hover'),
  'danger-on-solid': p('white'),
  'danger-subtle': p('red-subtle'),
  'danger-on-subtle': p('red-text'),
  'danger-border': p('red-border'),

  control: p('white'),
  'control-foreground': p('gray-900'),
  'control-hover': p('gray-50'),
  'control-active': p('gray-200'),
  'control-primary': p('blue'),
  'control-primary-foreground': p('white'),
  'control-primary-hover': p('blue-hover'),
  'control-primary-active': p('blue-active'),
  'control-ghost-hover': p('ink-6'),
  'control-ghost-active': p('ink-10'),
  'control-latched': p('gray-200'),
  'control-primary-latched': p('blue-active'),
  checked: p('blue'),
  'on-checked': p('white'),
  popover: p('glass-light'),
  'popover-border': p('ink-10'),
  'focus-ring': p('blue-ring'),
  caption: p('gray-300'),
  'caption-foreground': p('ink-50'),
  'caption-close': p('traffic-red'),
  'caption-minimize': p('traffic-yellow'),
  'caption-maximize': p('traffic-green'),
  'caption-inactive': p('gray-300'),
  'table-header': p('white'),
  'table-header-foreground': p('gray-600'),
  'table-stripe': p('gray-50'),
  'table-row-hover': p('ink-4'),
  track: p('gray-200'),
  progress: p('blue'),
  'scroll-thumb': p('ink-25'),
  'scroll-track': p('transparent'),
  'tooltip-border': p('ink-15'),
  groupbox: p('ink-4'),
  'groupbox-face': p('transparent'),
  'field-button': p('transparent'),
  'field-caret': p('blue'),
}

/** Semantic colours, dark. */
export const modernDarkColor: Record<SemanticColorName, string> = {
  ...modernLightColor,
  background: p('gray-925'),
  desktop: p('desktop-dark'),
  card: p('gray-850'),
  muted: p('gray-850'),
  accent: p('light-4'),
  'surface-active': p('gray-800'),
  'surface-disabled': p('gray-850'),
  skeleton: p('gray-800'),
  input: p('gray-925'),
  'tooltip-bg': p('gray-800'),

  foreground: p('gray-100'),
  'muted-foreground': p('gray-250'),
  'text-subtle': p('gray-400'),
  'text-disabled': p('gray-500'),
  link: p('blue-link-dark'),

  border: p('gray-750'),
  'border-strong': p('gray-500'),
  'border-subtle': p('gray-850'),
  ring: p('blue-link-dark'),
  'bevel-light': p('gray-750'),
  'bevel-shadow': p('gray-750'),
  'bevel-dark': p('gray-600'),

  'titlebar-from': p('gray-850'),
  'titlebar-to': p('gray-850'),
  'titlebar-inactive-from': p('gray-925'),
  'titlebar-inactive-to': p('gray-925'),
  'titlebar-foreground': p('gray-100'),
  'titlebar-inactive-foreground': p('gray-500'),

  'neutral-solid': p('gray-600'),
  'neutral-solid-hover': p('gray-700'),
  'neutral-subtle': p('gray-800'),
  'neutral-on-subtle': p('gray-150'),
  'neutral-border': p('gray-750'),

  'primary-subtle': p('blue-subtle-dark'),
  'primary-on-subtle': p('blue-text-dark'),
  'primary-border': p('blue-border-dark'),
  'success-subtle': p('green-subtle-dark'),
  'success-on-subtle': p('green-text-dark'),
  'success-border': p('green-border-dark'),
  'warning-subtle': p('orange-subtle-dark'),
  'warning-on-subtle': p('orange-text-dark'),
  'warning-border': p('orange-border-dark'),
  'danger-subtle': p('red-subtle-dark'),
  'danger-on-subtle': p('red-text-dark'),
  'danger-border': p('red-border-dark'),

  control: p('gray-750'),
  'control-foreground': p('gray-100'),
  'control-hover': p('gray-700'),
  'control-active': p('gray-600'),
  'control-ghost-hover': p('light-8'),
  'control-ghost-active': p('light-12'),
  'control-latched': p('gray-700'),
  'control-primary-latched': p('blue-active'),
  popover: p('glass-dark'),
  'popover-border': p('light-12'),
  'focus-ring': p('blue-ring-dark'),
  caption: p('gray-700'),
  'caption-inactive': p('gray-700'),
  'table-header': p('gray-925'),
  'table-header-foreground': p('gray-500'),
  'table-stripe': p('light-4'),
  'table-row-hover': p('light-4'),
  track: p('gray-800'),
  progress: p('blue-link-dark'),
  'scroll-thumb': p('light-25'),
  'tooltip-border': p('light-12'),
  groupbox: p('light-4'),
}

/** Shadows, light. Soft and outside the box, where Windows 98's bevels are hard and inside it. */
export const modernLightShadow: Record<ShadowName, string> = {
  none: 'none',
  raised: `0 0 0 1px ${p('ink-12')}, 0 1px 2px ${p('ink-10')}`,
  window: `0 0 0 1px ${p('ink-12')}, 0 2px 6px ${p('ink-10')}, 0 16px 40px ${p('ink-25')}`,
  'raised-default': `0 0 0 1px ${p('ink-10')}, 0 1px 2px ${p('ink-15')}`,
  pressed: `0 0 0 1px ${p('ink-15')}`,
  sunken: `inset 0 0 0 1px ${p('gray-500')}, inset 0 1px 1px ${p('ink-4')}`,
  status: 'none',
  etched: `inset 0 0 0 1px ${p('ink-8')}`,
  'raised-thin': 'none',
  popover: `0 0 0 1px ${p('ink-10')}, 0 10px 30px ${p('ink-15')}`,
  table: `inset 0 0 0 1px ${p('gray-300')}`,
  header: `inset 0 -1px 0 ${p('gray-300')}`,
  caption: `inset 0 0 0 0.5px ${p('ink-15')}`,
  statusbar: `inset 0 1px 0 ${p('gray-300')}`,
  titlebar: `inset 0 -1px 0 ${p('gray-250')}`,
  'scroll-thumb': 'none',
  'field-button': 'none',
  'latched-ghost': 'none',
  checked: `inset 0 0 0 1px ${p('ink-10')}`,
  'scroll-x': `inset -1px 0 ${p('gray-300')}`,
  'sticky-header': `inset 0 -1px 0 ${p('gray-300')}`,
}

/** Shadows, dark: edges drawn in light ink, because a dark shadow on a dark page shows nothing. */
export const modernDarkShadow: Record<ShadowName, string> = {
  ...modernLightShadow,
  raised: `0 0 0 1px ${p('ink-50')}, inset 0 1px 0 ${p('light-12')}`,
  window: `0 0 0 1px ${p('light-12')}, 0 16px 40px ${p('ink-50')}`,
  'raised-default': `0 0 0 1px ${p('ink-50')}, inset 0 1px 0 ${p('light-16')}`,
  pressed: `0 0 0 1px ${p('ink-50')}`,
  sunken: `inset 0 0 0 1px ${p('gray-500')}`,
  etched: `inset 0 0 0 1px ${p('light-8')}`,
  popover: `0 0 0 1px ${p('light-12')}, 0 10px 30px ${p('ink-50')}`,
  table: `inset 0 0 0 1px ${p('gray-750')}`,
  header: `inset 0 -1px 0 ${p('gray-750')}`,
  caption: `inset 0 0 0 0.5px ${p('ink-25')}`,
  statusbar: `inset 0 1px 0 ${p('gray-750')}`,
  titlebar: `inset 0 -1px 0 ${p('ink-50')}`,
  'scroll-x': `inset -1px 0 ${p('gray-750')}`,
  'sticky-header': `inset 0 -1px 0 ${p('gray-750')}`,
}

/** Sizes. Roomier than Windows 98's, for a pointer and a finger alike. */
export const modernSize: Record<SizeName, string> = {
  'control-xs': '24px',
  'control-sm': '28px',
  'control-md': '32px',
  'control-lg': '40px',
  'icon-xs': '24px',
  'icon-sm': '28px',
  'icon-md': '32px',
  'icon-lg': '40px',
  'button-min-xs': '0px',
  'button-min-sm': '0px',
  'button-min-md': '72px',
  'button-min-lg': '88px',
  'button-px-xs': '0.5rem',
  'button-px-sm': '0.625rem',
  'button-px-md': '0.875rem',
  'button-px-lg': '1.125rem',
  'field-px': '0.5rem',
  'field-px-lg': '0.75rem',
  check: '16px',
  radio: '16px',
  titlebar: '38px',
  'caption-w': '12px',
  'caption-h': '12px',
  'caption-gap': '8px',
  'caption-close-gap': '0px',
  'titlebar-px': '12px',
  'title-inset-start': '72px',
  'title-inset-end': '72px',
  frame: '0px',
  'dialog-px': '20px',
  'dialog-pt': '16px',
  'dialog-footer-pt': '14px',
  'dialog-footer-pb': '20px',
  item: '28px',
  'popover-inset': '5px',
  'row-sm': '30px',
  'row-md': '36px',
  'chip-sm': '24px',
  'chip-md': '28px',
  'badge-px-sm': '7px',
  'badge-px-md': '8px',
  'badge-dot': '6px',
  'empty-p-sm': '16px',
  'empty-p-md': '32px',
  'empty-p-lg': '48px',
  'empty-gap': '12px',
  'tooltip-px': '0.5rem',
  'tooltip-py': '3px',
  statusbar: '28px',
  progress: '6px',
  'progress-inset': '0px',
  'progress-fill': '6px',
  'progress-block': '1px',
  'progress-period': '1px',
  scrollbar: '10px',
  'scroll-button': '0px',
  'scroll-inset': '2px',
  'groupbox-top': '22px',
  'groupbox-pt': '2.25rem',
  'groupbox-legend-x': '0px',
  'groupbox-legend-px': '0px',
}

/** Corner radii, set directly: each is a length here, not a multiple of `--radius`. */
export const modernRadius: Record<Exclude<RadiusName, 'full'>, string> = {
  none: '0px',
  xs: '4px',
  sm: '5px',
  md: '7px',
  lg: '10px',
  xl: '12px',
  pill: '9999px',
}

/** Style switches. */
export const modernStyle: Record<StyleName, string> = {
  'focus-label-width': '0px',
  'focus-ring-width': '2px',
  'focus-ring-style': 'solid',
  'focus-outer-width': '3px',
  'focus-outer-offset': '0px',
  'press-shift': '0px',
  'press-brightness': '0.85',
  'dither-image': 'none',
  'loading-image': 'none',
  'animate-loading': 'rk-pulse 1.6s ease-in-out infinite',
  'duration-control': '120ms',
  'animate-overlay-in': 'rk-overlay-in 160ms cubic-bezier(0, 0, 0.2, 1)',
  'etch-width': '0px',
  'caption-order': '-1',
  'close-order': '-1',
  'overlay-bg': 'var(--color-modern-ink-15)',
  'link-decoration': 'none',
  'invalid-width': '1px',
  'footer-direction': 'row-reverse',
  'empty-direction': 'column',
  'empty-align': 'center',
  'titlebar-align': 'center',
  'titlebar-balance': '60px',
  'caption-glyph-opacity': '0',
  'popover-backdrop': 'blur(24px) saturate(180%)',
  'scrollbar-buttons': 'none',
  'glyph-scale': '1.4',
  'radio-fill': '100%',
  'radio-dot-r': '3px',
  'radio-edge': '1px',
  'icon-pixels': 'none',
  'icon-glyphs': ' ',
  'icon-fill': 'currentColor',
  'icon-tone-danger': 'var(--color-danger-solid)',
  'icon-tone-warning': 'var(--color-warning-solid)',
  'icon-tone-info': 'var(--color-primary-solid)',
  'icon-tone-success': 'var(--color-success-solid)',
  'icon-tone-folder': 'var(--color-primary-solid)',
}

/** Typefaces: the platform's own. Nothing to load. */
export const modernFont = {
  sans: [
    '-apple-system',
    'BlinkMacSystemFont',
    '"SF Pro Text"',
    '"Inter"',
    '"Segoe UI"',
    'system-ui',
    'sans-serif',
  ].join(', '),
  mono: ['ui-monospace', '"SF Mono"', 'Menlo', 'Consolas', 'monospace'].join(', '),
} as const

/** Type sizes that differ from Windows 98's. Size and line height, as in `fontSize`. */
export const modernFontSize = {
  ui: { size: '0.8125rem', lineHeight: '1.125rem' },
  heading: { size: '0.9375rem', lineHeight: '1.25rem' },
  mono: { size: '0.75rem', lineHeight: '1.125rem' },
  'doc-mono': { size: '0.875rem', lineHeight: '1.375rem' },
} as const

/** Font weights that differ: emphasis is semibold. */
export const modernFontWeight = {
  strong: '600',
} as const
